import type { Metadata } from "next";
import { Alumni_Sans_SC, Geist ,Inter_Tight} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const alumni = Alumni_Sans_SC({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-alumni",
});

const interTight = Inter_Tight({
  subsets: ["latin"],
  weight: ["200","400", "600", "700"],
  variable: "--font-inter-tight",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${alumni.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
